### ISSUE TITLE
Jessie : AlternC should allow HTTPS panel access for different host names

### ISSUE THREAD

**Issue by albancrommer** [AlternC/AlternC#106] opened 2016-07-13 10:12 UTC
There is a hard filtering in the config PHP file for HTTPS calls to panel whose HOST does not match the AlternC panel HOSTNAME set in config.

With Letsencrypt, this is a bad thing : all domains now can have a HTTPS panel access.

**Comment by innoticFR** [comment] 2016-07-13 10:48
This is a duplicate of https://github.com/AlternC/AlternC/issues/69

**Closed** 2016-08-09 14:44 UTC
