### ISSUE TITLE
Table 'alternc.certif_alias' doesn't exist

### ISSUE THREAD

**Issue by skhaen** [AlternC/AlternC#13] opened 2015-09-28 09:36 UTC
Après une nouvelle installation d'alternc 3.2.8 + alternc-ssl, j'ai l'erreur suivante : 

ERROR 1146 (42S02) at line 1: Table 'alternc.certif_alias' doesn't exist

**Comment by vincib** [comment] 2016-08-26 15:06
can't reproduce, may be fixed in 3.2.11

**Closed by vincib** 2016-08-26 15:06 UTC
Labels: bug

**Comment by camlafit** [comment] 2017-10-08 13:15
Tested on fresh install wheezy, no more pb on 3.2.11 nightly
