### ISSUE TITLE
AlternC on debian bullseye and bookworm? 

### ISSUE THREAD

**Issue by ulvida** [AlternC/AlternC#542] opened 2023-09-16 10:42 UTC
We have several AlternC instances, last of them on debian buster, with php 7.3. They are installed from Kumbit repos, and I could never upgrade it to bullseye or install a new one. At least with the same install procedure. The .deb package has a specific dependency on php7.3, so, as such, not upgradable.

Does presently AlternC run on debian bullseye? Or, better, now, on debian bookworm? If yes, how should I install it? Neither duckduckgo o google could help me.

At home or at work, in France, Bolivia or Uruguay, I've been using Altern for more than 20 years. Wouldn't like to loose it. Now my colleagues have found an interesting alternative, hestiacp, but still AlternC has it's specific behaviours that are good in many cases.

Merci d'avance, chers amis.

**Comment by ulvida** [comment] 2023-10-03 11:23
hello freinds, so ¿no package or basic cookbook to install alternc on debian bulleye or bookworms?

**Comment by camlafit** [comment] 2023-10-06 14:55
Hi

It's in progress. Actualy we have merge all delay from koumbit:pu evolve. Then we can provide a common package.
Actually we must provide a new RC and test to patch all regression from koumbit.
After we have to backport some evolve from 3.3 to prevent also any regression

3.5 should support buster/bulleye
3.6 could be support bookworm

**Comment by vincib** [comment] 2023-12-07 09:43
Hi,

I started working on that recently, starting from the koumbit bullseye_support branch, and adding support for both bullseye & bookworm. I hope we could do a package that would work fine on both (PHP7.4 & PHP8.2 + some packages and misc fixes)

as of now what has been done : 

- discovered that vlogger package does not exist in bookworm (we'd have to package it ourselves) https://packages.debian.org/search?keywords=vlogger
- fixed most php incompatibilities (magic_quotes_gpc() removal, each() removal, some is_object() or isset() to add...) 
- fixed the class constructors that changes from <classname>() to __construct()
- found that the mariadb/mysql part does not work yet: the permission system seems to be quite different, so we may have to change some code there. 

as of now that's all, let's follow on https://github.com/AlternC/AlternC/tree/issue-542 branch !

**Comment by vincib** [comment] 2023-12-08 09:39
I'm adding here what else I found (not fixed yet):

- mariadb 10.11 is not accepting users who logged via "localhost" or "127.0.0.1" (which means "by unix socket") if their host field is "%". it MUST be "localhost" in that case. So if the mysql is local, we need to set "client" in db_servers to "localhost" and not "%". Note that this works on debian 10 & 11 too. (mariadb 10.5 & 10.3)

**Comment by vincib** [comment] 2024-07-07 15:37
Merged today the latest changes on main to issue-542 branch, to ensure we can still follow the changes on both. No conflicts. will test that on a bookworm

**Comment by camlafit** [comment] 2024-08-08 08:47
A rebase would be better :/ 
I've tried to check change but merge "rollback" also history from 3.3

I'll check to rebase branch over main to catch only specifics changes :)

**Comment by camlafit** [comment] 2024-08-28 12:47
Hello

Ok I've understood why this patch looks so ugly, with too many commit unrelated. 
This work as started before rc2 and then many file are backported during last merge but the diff looks coherent.

PR will be done as this.

**Closed** 2024-08-28 12:51 UTC
